#!/bin/sh

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=192.168.2.22
#eth0.netmask=255.255.255.0
eth0.serverip=192.168.1.70
#eth0.gateway=192.168.2.1
#eth0.ethaddr=00:0A:0B:0C:0D:0E
#eth1.ethaddr=00:1A:1B:1C:1D:1E
#eth2.ethaddr=00:2A:2B:2C:2D:2E

# can be either 'nfs', 'tftp' , 'nor' , 'nand' and 'sata'
kernel_loc=nand
#kernel_loc=nor
#kernel_loc=sata
# can be either 'net', 'nor' ,'initrd' , 'nand' and 'sata'
rootfs_loc=nand
#rootfs_loc=nor
#rootfs_loc=sata

# barebox images
uloaderimage=microloader-c2kevm.bin
bareboximage=barebox-c2kevm.bin

# MFG images for NAND flash
mfg_kernel_img=uImage_MFG
mfg_rootfs_img=rootfs_ubi.img_MFG

# can be either 'jffs2' , 'ubifs' or 'ext4
#rootfs_type=jffs2
rootfs_type=ubifs
#rootfs_type=ext4
rootfsimage=root.$rootfs_type-128k

# The image type of the kernel. Can be uimage, zimage, raw, or raw_lzo
kernelimage_type=uimage
kernelimage=uImage

#nfsroot="$eth0.serverip:/opt/work/busybox/rootfs_arm"

spi_parts="256k(uloader)ro,512k(barebox)ro,256k(env)"
spi_device="spi0.0"

nand_device="comcertonand"
#nand_parts="1024k(barebox)ro,1024k(bareboxenv),4M(kernel),-(rootfs)"
nand_parts="10M(config),10M(kernel1),110M(rootfs1),10M(kernel2),110M(rootfs2),-(reserved)"
#rootfs_mtdblock_nand=8
rootfs_mtdblock_nand=2

#nor_parts="128k(uloader)ro,512k(barebox)ro,128k(env),4M(kernel),48M(rootfs)"
#nor_device="comcertoflash.0"
#rootfs_mtdblock_nor=4

autoboot_timeout=3

usb3_internal_clk="yes"

bootargs="console=ttyS0,115200n8, init=/etc/preinit pcie_gen1_only=yes "
bootargs="$bootargs mac_addr=$eth0.ethaddr,$eth1.ethaddr,$eth2.ethaddr"

# boot partition
next_bootfrom="1"
curr_bootfrom="1"

# partition layout
kernel_mtd_1=4
sysimg_mtd_1=5
kernel_mtd_2=6
sysimg_mtd_2=7

# MODEL ID for STG-540
MODEL_ID="B403"
fwversion_1="V5.21(ABAG.2)"
revision_1="51163"
modelid_1="B403"
core_checksum_1="e94bd7a8256f7658127e4b06a63b902a"
zld_checksum_1="d032eaf4ad157ca1581d7fa2c9fd4e84"
romfile_checksum_1="9D34"
img_checksum_1="b250972b15b49504268ddb285fa1c6ea"
fwversion_2="V5.21(ABAG.2)"
revision_2="51163"
modelid_2="B403"
core_checksum_2="e94bd7a8256f7658127e4b06a63b902a"
zld_checksum_2="d032eaf4ad157ca1581d7fa2c9fd4e84"
romfile_checksum_2="9D34"
img_checksum_2="b250972b15b49504268ddb285fa1c6ea"
ethaddr="BC:99:11:5B:80:F5"
eth2addr="BC:99:11:5B:80:F6"
serial_number="S190Z03029691"
change_boot_part="0"
